services:

  frankenphp:
    image: dunglas/frankenphp:1.12.4
    ports:
      - "81:80"
    volumes:
      - ./Caddyfile_frankenphp:/etc/frankenphp/Caddyfile:ro
      - ./src:/srv
      - caddy_data_frankenphp:/data

volumes:
  caddy_data_fpm:
  caddy_data_frankenphp:

networks:
  app-network:
    # Optional: use a specific network name
